### ISSUE TITLE
NotYetConnectedException

### ISSUE THREAD

**Issue by lodenrogue** [migzai/irc-api#36]
When giving an invalid server name in the ircApi.connect() method the connection fails and the application tries to close the connection in the AbstractIRCSession class but this causes the application to throw an exception because there is no valid connection established.

```
Caused by: java.nio.channels.NotYetConnectedException
        at java.base/sun.nio.ch.SocketChannelImpl.ensureOpenAndConnected(SocketChannelImpl.java:178)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:452)
        at com.ircclouds.irc.api.comms.SSLSocketChannelConnection.wrapAndWrite(SSLSocketChannelConnection.java:183)
        at com.ircclouds.irc.api.comms.SSLSocketChannelConnection.processHandshake(SSLSocketChannelConnection.java:115)
        at com.ircclouds.irc.api.comms.SSLSocketChannelConnection.doAnyPendingHandshake(SSLSocketChannelConnection.java:103)
        at com.ircclouds.irc.api.comms.SSLSocketChannelConnection.close(SSLSocketChannelConnection.java:87)
        at com.ircclouds.irc.api.AbstractIRCSession.close(AbstractIRCSession.java:120)
        at com.ircclouds.irc.api.IRCApiImpl.closeSession(IRCApiImpl.java:463)
        at com.ircclouds.irc.api.IRCApiImpl.connect(IRCApiImpl.java:117)
```

My expectation is that this exception is propagated to the callback onFailure() method and no exception is thrown.

**Comment by lodenrogue** [comment]
Closing as it seems this project is no longer being maintained
